services:
  #jdbc:postgresql://postgres-db:5432/databasesql
  postgres:
    image: postgres:16
    container_name: postgresDataBase
    restart: always
    ports:
      - "5432:5432" #puerto por defecto
      - "5433:5433"  #puerto secundario por si ocurre un error
    environment:
      POSTGRES_DB: databasesql
      POSTGRES_USER: admin    #usuario
      POSTGRES_PASSWORD: admin123   #clave
    volumes:
      - postgres-data:/var/lib/postgresql/data 

volumes:
  postgres-data: